openapi: 3.0.3
info:
  description: This api publishes stock aggregates using Polygon.io S3 Storage. This
    data is published using Kafka.
  title: A trade data api
  version: 1.0.0
servers:
  - url: http://localhost:8080
  - url: http://localhost:7001
paths:
  /v1/fetch-aggregate-data:
    post:
      operationId: v1_fetch_aggregate_data_post
      responses:
        "200":
          description: Fetching data successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FetchAggregateDataResult"
      summary: Fetches minute and daily aggregates dating back 5 years
      x-openapi-router-controller: app.controllers.default_controller
  /v1/publish-aggregate-data:
    post:
      operationId: v1_publish_aggregate_data_post
      responses:
        "200":
          description: Publishing data successful
      summary: Publish aggregate data to Kafka
      x-openapi-router-controller: app.controllers.default_controller
  /v1/purge-aggregate-data:
    post:
      operationId: v1_purge_aggregate_data_post
      responses:
        "200":
          description: Purging data successful
      summary: Purge published data to Kafka
      x-openapi-router-controller: app.controllers.default_controller

  /v1/test-publish:
    post:
      operationId: v1_test_publish
      responses:
        "200":
          description: Published a test message
      summary: Testing publish
      x-openapi-router-controller: app.controllers.test_controller
components:
  schemas:
    FetchAggregateDataResult:
      type: object
      properties:
        pages_fetched:
          type: integer
          description: Number of S3 pages fetched from Polygon
        day_agg_downloaded:
          type: integer
          description: Number of daily aggregate files downloaded
        min_agg_downloaded:
          type: integer
          description: Number of minute aggregate files downloaded
      required:
        - pages_fetched
        - day_agg_downloaded
        - min_agg_downloaded