openapi: 3.0.3
info:
  title: "A trade data api"
  version: "1.0.0"
  description: "This api publishes stock aggregates using Polygon.io S3 Storage. This data is published using Kafka."
paths:
  /v1/fetch-aggregate-data:
    post:
      summary: "Fetches minute and daily aggregates dating back 5 years"
      responses:
        '200':
          description: "Fetching data successful"
  /v1/publish-aggregate-data:
    post:
      summary: "Publish aggregate data to Kafka"
      responses:
        '200':
          description: "Publishing data successful"